behaviors:
  DroneDefender:
    trainer_type: ppo
    # init_path: results\phase2_33obs\DroneFlight\checkpoint.pt
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 1.0e-3
      beta_schedule: linear
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant

    network_settings:
      normalize: true
      hidden_units: 256  
      num_layers: 5

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    max_steps: 1.0e8
    time_horizon: 64
    summary_freq: 10000

  DroneAttacker:
    trainer_type: ppo
    # init_path: results\phase3_5x256_03\DroneAttacker\checkpoint.pt
    # init_path: results\phase2_4x128\DroneFlight\checkpoint.pt

    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 1.0e-3
      beta_schedule: linear
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant

    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 4

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    max_steps: 1.0e8
    time_horizon: 64
    summary_freq: 10000
